unique_ids:
  assets:
    standard-page.html: OJ3Z3AKPXLDCLTWUPE5XT3SVCSF3JGST
    theme.css: WPWHOWT2XB5YL266N3HQZ3RSY4I5LNGI
  forms:
    Form1: WLG6Q37OX4MXTWJQVXEYXIQJ6I254ASV
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1732704239032245408288959.69247'
